apiVersion: v1
kind: Namespace
metadata:
  name: tool
  labels:
    istio-injection: enabled
---
kind: Service
apiVersion: v1
metadata:
  name: grpc-json-proxy
  namespace: tool
  labels:
    app: grpc-json-proxy
spec:
  ports:
    - name: http
      protocol: TCP
      port: 7001
      targetPort: 6565
  selector:
    app: grpc-json-proxy
  type: NodePort
  sessionAffinity: None
  externalTrafficPolicy: Cluster
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: grpc-json-proxy-stable
  namespace: tool
  labels:
    app: grpc-json-proxy
    version: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-json-proxy
      version: stable
  template:
    metadata:
      labels:
        app: grpc-json-proxy
        version: stable
    spec:
      containers:
        - name: grpc-json-proxy
          image: lshare/grpc-json-proxy:stable
          ports:
            - name: http
              containerPort: 7001
              protocol: TCP
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 1000m
              memory: 1000Mi
      imagePullSecrets:
        - name: default-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
